version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: kpsydesk-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: kpsydesk_db
      POSTGRES_USER: kpsydesk_admin
      POSTGRES_PASSWORD: kpsydesk_secure_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - kpsydesk-network

networks:
  kpsydesk-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
